// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.zhuldyz.service1;

public final class Service1Proto {
  private Service1Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetVitalSignsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:patientmonitoring.GetVitalSignsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string patient_id = 1;</code>
     */
    java.lang.String getPatientId();
    /**
     * <code>string patient_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getPatientIdBytes();
  }
  /**
   * Protobuf type {@code patientmonitoring.GetVitalSignsRequest}
   */
  public  static final class GetVitalSignsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:patientmonitoring.GetVitalSignsRequest)
      GetVitalSignsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetVitalSignsRequest.newBuilder() to construct.
    private GetVitalSignsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetVitalSignsRequest() {
      patientId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetVitalSignsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              patientId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_GetVitalSignsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_GetVitalSignsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest.class, ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest.Builder.class);
    }

    public static final int PATIENT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object patientId_;
    /**
     * <code>string patient_id = 1;</code>
     */
    public java.lang.String getPatientId() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientId_ = s;
        return s;
      }
    }
    /**
     * <code>string patient_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPatientIdBytes() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPatientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, patientId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPatientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, patientId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest)) {
        return super.equals(obj);
      }
      ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest other = (ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest) obj;

      boolean result = true;
      result = result && getPatientId()
          .equals(other.getPatientId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPatientId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code patientmonitoring.GetVitalSignsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:patientmonitoring.GetVitalSignsRequest)
        ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_GetVitalSignsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_GetVitalSignsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest.class, ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest.Builder.class);
      }

      // Construct using ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        patientId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_GetVitalSignsRequest_descriptor;
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest getDefaultInstanceForType() {
        return ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest build() {
        ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest buildPartial() {
        ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest result = new ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest(this);
        result.patientId_ = patientId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest) {
          return mergeFrom((ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest other) {
        if (other == ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest.getDefaultInstance()) return this;
        if (!other.getPatientId().isEmpty()) {
          patientId_ = other.patientId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object patientId_ = "";
      /**
       * <code>string patient_id = 1;</code>
       */
      public java.lang.String getPatientId() {
        java.lang.Object ref = patientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          patientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPatientIdBytes() {
        java.lang.Object ref = patientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder setPatientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        patientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder clearPatientId() {
        
        patientId_ = getDefaultInstance().getPatientId();
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder setPatientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        patientId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:patientmonitoring.GetVitalSignsRequest)
    }

    // @@protoc_insertion_point(class_scope:patientmonitoring.GetVitalSignsRequest)
    private static final ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest();
    }

    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetVitalSignsRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetVitalSignsRequest>() {
      @java.lang.Override
      public GetVitalSignsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetVitalSignsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetVitalSignsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetVitalSignsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.zhuldyz.service1.Service1Proto.GetVitalSignsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetVitalSignsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:patientmonitoring.GetVitalSignsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float blood_pressure = 1;</code>
     */
    float getBloodPressure();

    /**
     * <code>float temperature = 2;</code>
     */
    float getTemperature();
  }
  /**
   * Protobuf type {@code patientmonitoring.GetVitalSignsResponse}
   */
  public  static final class GetVitalSignsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:patientmonitoring.GetVitalSignsResponse)
      GetVitalSignsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetVitalSignsResponse.newBuilder() to construct.
    private GetVitalSignsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetVitalSignsResponse() {
      bloodPressure_ = 0F;
      temperature_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetVitalSignsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              bloodPressure_ = input.readFloat();
              break;
            }
            case 21: {

              temperature_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_GetVitalSignsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_GetVitalSignsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse.class, ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse.Builder.class);
    }

    public static final int BLOOD_PRESSURE_FIELD_NUMBER = 1;
    private float bloodPressure_;
    /**
     * <code>float blood_pressure = 1;</code>
     */
    public float getBloodPressure() {
      return bloodPressure_;
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 2;
    private float temperature_;
    /**
     * <code>float temperature = 2;</code>
     */
    public float getTemperature() {
      return temperature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (bloodPressure_ != 0F) {
        output.writeFloat(1, bloodPressure_);
      }
      if (temperature_ != 0F) {
        output.writeFloat(2, temperature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (bloodPressure_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, bloodPressure_);
      }
      if (temperature_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, temperature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse)) {
        return super.equals(obj);
      }
      ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse other = (ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getBloodPressure())
          == java.lang.Float.floatToIntBits(
              other.getBloodPressure()));
      result = result && (
          java.lang.Float.floatToIntBits(getTemperature())
          == java.lang.Float.floatToIntBits(
              other.getTemperature()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOOD_PRESSURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBloodPressure());
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTemperature());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code patientmonitoring.GetVitalSignsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:patientmonitoring.GetVitalSignsResponse)
        ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_GetVitalSignsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_GetVitalSignsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse.class, ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse.Builder.class);
      }

      // Construct using ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bloodPressure_ = 0F;

        temperature_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_GetVitalSignsResponse_descriptor;
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse getDefaultInstanceForType() {
        return ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse build() {
        ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse buildPartial() {
        ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse result = new ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse(this);
        result.bloodPressure_ = bloodPressure_;
        result.temperature_ = temperature_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse) {
          return mergeFrom((ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse other) {
        if (other == ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse.getDefaultInstance()) return this;
        if (other.getBloodPressure() != 0F) {
          setBloodPressure(other.getBloodPressure());
        }
        if (other.getTemperature() != 0F) {
          setTemperature(other.getTemperature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float bloodPressure_ ;
      /**
       * <code>float blood_pressure = 1;</code>
       */
      public float getBloodPressure() {
        return bloodPressure_;
      }
      /**
       * <code>float blood_pressure = 1;</code>
       */
      public Builder setBloodPressure(float value) {
        
        bloodPressure_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float blood_pressure = 1;</code>
       */
      public Builder clearBloodPressure() {
        
        bloodPressure_ = 0F;
        onChanged();
        return this;
      }

      private float temperature_ ;
      /**
       * <code>float temperature = 2;</code>
       */
      public float getTemperature() {
        return temperature_;
      }
      /**
       * <code>float temperature = 2;</code>
       */
      public Builder setTemperature(float value) {
        
        temperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float temperature = 2;</code>
       */
      public Builder clearTemperature() {
        
        temperature_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:patientmonitoring.GetVitalSignsResponse)
    }

    // @@protoc_insertion_point(class_scope:patientmonitoring.GetVitalSignsResponse)
    private static final ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse();
    }

    public static ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetVitalSignsResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetVitalSignsResponse>() {
      @java.lang.Override
      public GetVitalSignsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetVitalSignsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetVitalSignsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetVitalSignsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.zhuldyz.service1.Service1Proto.GetVitalSignsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SetAlertValueRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:patientmonitoring.SetAlertValueRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string patient_id = 1;</code>
     */
    java.lang.String getPatientId();
    /**
     * <code>string patient_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getPatientIdBytes();

    /**
     * <code>float blood_pressure_value = 2;</code>
     */
    float getBloodPressureValue();

    /**
     * <code>float temperature_value = 3;</code>
     */
    float getTemperatureValue();
  }
  /**
   * Protobuf type {@code patientmonitoring.SetAlertValueRequest}
   */
  public  static final class SetAlertValueRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:patientmonitoring.SetAlertValueRequest)
      SetAlertValueRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SetAlertValueRequest.newBuilder() to construct.
    private SetAlertValueRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SetAlertValueRequest() {
      patientId_ = "";
      bloodPressureValue_ = 0F;
      temperatureValue_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SetAlertValueRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              patientId_ = s;
              break;
            }
            case 21: {

              bloodPressureValue_ = input.readFloat();
              break;
            }
            case 29: {

              temperatureValue_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_SetAlertValueRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_SetAlertValueRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest.class, ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest.Builder.class);
    }

    public static final int PATIENT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object patientId_;
    /**
     * <code>string patient_id = 1;</code>
     */
    public java.lang.String getPatientId() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientId_ = s;
        return s;
      }
    }
    /**
     * <code>string patient_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPatientIdBytes() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLOOD_PRESSURE_VALUE_FIELD_NUMBER = 2;
    private float bloodPressureValue_;
    /**
     * <code>float blood_pressure_value = 2;</code>
     */
    public float getBloodPressureValue() {
      return bloodPressureValue_;
    }

    public static final int TEMPERATURE_VALUE_FIELD_NUMBER = 3;
    private float temperatureValue_;
    /**
     * <code>float temperature_value = 3;</code>
     */
    public float getTemperatureValue() {
      return temperatureValue_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPatientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, patientId_);
      }
      if (bloodPressureValue_ != 0F) {
        output.writeFloat(2, bloodPressureValue_);
      }
      if (temperatureValue_ != 0F) {
        output.writeFloat(3, temperatureValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPatientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, patientId_);
      }
      if (bloodPressureValue_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, bloodPressureValue_);
      }
      if (temperatureValue_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, temperatureValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest)) {
        return super.equals(obj);
      }
      ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest other = (ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest) obj;

      boolean result = true;
      result = result && getPatientId()
          .equals(other.getPatientId());
      result = result && (
          java.lang.Float.floatToIntBits(getBloodPressureValue())
          == java.lang.Float.floatToIntBits(
              other.getBloodPressureValue()));
      result = result && (
          java.lang.Float.floatToIntBits(getTemperatureValue())
          == java.lang.Float.floatToIntBits(
              other.getTemperatureValue()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPatientId().hashCode();
      hash = (37 * hash) + BLOOD_PRESSURE_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBloodPressureValue());
      hash = (37 * hash) + TEMPERATURE_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTemperatureValue());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code patientmonitoring.SetAlertValueRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:patientmonitoring.SetAlertValueRequest)
        ds.zhuldyz.service1.Service1Proto.SetAlertValueRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_SetAlertValueRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_SetAlertValueRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest.class, ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest.Builder.class);
      }

      // Construct using ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        patientId_ = "";

        bloodPressureValue_ = 0F;

        temperatureValue_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_SetAlertValueRequest_descriptor;
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest getDefaultInstanceForType() {
        return ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest build() {
        ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest buildPartial() {
        ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest result = new ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest(this);
        result.patientId_ = patientId_;
        result.bloodPressureValue_ = bloodPressureValue_;
        result.temperatureValue_ = temperatureValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest) {
          return mergeFrom((ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest other) {
        if (other == ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest.getDefaultInstance()) return this;
        if (!other.getPatientId().isEmpty()) {
          patientId_ = other.patientId_;
          onChanged();
        }
        if (other.getBloodPressureValue() != 0F) {
          setBloodPressureValue(other.getBloodPressureValue());
        }
        if (other.getTemperatureValue() != 0F) {
          setTemperatureValue(other.getTemperatureValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object patientId_ = "";
      /**
       * <code>string patient_id = 1;</code>
       */
      public java.lang.String getPatientId() {
        java.lang.Object ref = patientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          patientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPatientIdBytes() {
        java.lang.Object ref = patientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder setPatientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        patientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder clearPatientId() {
        
        patientId_ = getDefaultInstance().getPatientId();
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder setPatientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        patientId_ = value;
        onChanged();
        return this;
      }

      private float bloodPressureValue_ ;
      /**
       * <code>float blood_pressure_value = 2;</code>
       */
      public float getBloodPressureValue() {
        return bloodPressureValue_;
      }
      /**
       * <code>float blood_pressure_value = 2;</code>
       */
      public Builder setBloodPressureValue(float value) {
        
        bloodPressureValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float blood_pressure_value = 2;</code>
       */
      public Builder clearBloodPressureValue() {
        
        bloodPressureValue_ = 0F;
        onChanged();
        return this;
      }

      private float temperatureValue_ ;
      /**
       * <code>float temperature_value = 3;</code>
       */
      public float getTemperatureValue() {
        return temperatureValue_;
      }
      /**
       * <code>float temperature_value = 3;</code>
       */
      public Builder setTemperatureValue(float value) {
        
        temperatureValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float temperature_value = 3;</code>
       */
      public Builder clearTemperatureValue() {
        
        temperatureValue_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:patientmonitoring.SetAlertValueRequest)
    }

    // @@protoc_insertion_point(class_scope:patientmonitoring.SetAlertValueRequest)
    private static final ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest();
    }

    public static ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SetAlertValueRequest>
        PARSER = new com.google.protobuf.AbstractParser<SetAlertValueRequest>() {
      @java.lang.Override
      public SetAlertValueRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetAlertValueRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SetAlertValueRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SetAlertValueRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.zhuldyz.service1.Service1Proto.SetAlertValueRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AcknowledgmentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:patientmonitoring.Acknowledgment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code patientmonitoring.Acknowledgment}
   */
  public  static final class Acknowledgment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:patientmonitoring.Acknowledgment)
      AcknowledgmentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Acknowledgment.newBuilder() to construct.
    private Acknowledgment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Acknowledgment() {
      success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Acknowledgment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              success_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_Acknowledgment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_Acknowledgment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.zhuldyz.service1.Service1Proto.Acknowledgment.class, ds.zhuldyz.service1.Service1Proto.Acknowledgment.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (success_ != false) {
        output.writeBool(1, success_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.zhuldyz.service1.Service1Proto.Acknowledgment)) {
        return super.equals(obj);
      }
      ds.zhuldyz.service1.Service1Proto.Acknowledgment other = (ds.zhuldyz.service1.Service1Proto.Acknowledgment) obj;

      boolean result = true;
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.zhuldyz.service1.Service1Proto.Acknowledgment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code patientmonitoring.Acknowledgment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:patientmonitoring.Acknowledgment)
        ds.zhuldyz.service1.Service1Proto.AcknowledgmentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_Acknowledgment_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_Acknowledgment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.zhuldyz.service1.Service1Proto.Acknowledgment.class, ds.zhuldyz.service1.Service1Proto.Acknowledgment.Builder.class);
      }

      // Construct using ds.zhuldyz.service1.Service1Proto.Acknowledgment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        success_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.zhuldyz.service1.Service1Proto.internal_static_patientmonitoring_Acknowledgment_descriptor;
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.Acknowledgment getDefaultInstanceForType() {
        return ds.zhuldyz.service1.Service1Proto.Acknowledgment.getDefaultInstance();
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.Acknowledgment build() {
        ds.zhuldyz.service1.Service1Proto.Acknowledgment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.zhuldyz.service1.Service1Proto.Acknowledgment buildPartial() {
        ds.zhuldyz.service1.Service1Proto.Acknowledgment result = new ds.zhuldyz.service1.Service1Proto.Acknowledgment(this);
        result.success_ = success_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.zhuldyz.service1.Service1Proto.Acknowledgment) {
          return mergeFrom((ds.zhuldyz.service1.Service1Proto.Acknowledgment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.zhuldyz.service1.Service1Proto.Acknowledgment other) {
        if (other == ds.zhuldyz.service1.Service1Proto.Acknowledgment.getDefaultInstance()) return this;
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.zhuldyz.service1.Service1Proto.Acknowledgment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.zhuldyz.service1.Service1Proto.Acknowledgment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 1;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:patientmonitoring.Acknowledgment)
    }

    // @@protoc_insertion_point(class_scope:patientmonitoring.Acknowledgment)
    private static final ds.zhuldyz.service1.Service1Proto.Acknowledgment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.zhuldyz.service1.Service1Proto.Acknowledgment();
    }

    public static ds.zhuldyz.service1.Service1Proto.Acknowledgment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Acknowledgment>
        PARSER = new com.google.protobuf.AbstractParser<Acknowledgment>() {
      @java.lang.Override
      public Acknowledgment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Acknowledgment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Acknowledgment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Acknowledgment> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.zhuldyz.service1.Service1Proto.Acknowledgment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientmonitoring_GetVitalSignsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientmonitoring_GetVitalSignsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientmonitoring_GetVitalSignsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientmonitoring_GetVitalSignsResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientmonitoring_SetAlertValueRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientmonitoring_SetAlertValueRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_patientmonitoring_Acknowledgment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_patientmonitoring_Acknowledgment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\021patientmonitoring\"*\n\024G" +
      "etVitalSignsRequest\022\022\n\npatient_id\030\001 \001(\t\"" +
      "D\n\025GetVitalSignsResponse\022\026\n\016blood_pressu" +
      "re\030\001 \001(\002\022\023\n\013temperature\030\002 \001(\002\"c\n\024SetAler" +
      "tValueRequest\022\022\n\npatient_id\030\001 \001(\t\022\034\n\024blo" +
      "od_pressure_value\030\002 \001(\002\022\031\n\021temperature_v" +
      "alue\030\003 \001(\002\"!\n\016Acknowledgment\022\017\n\007success\030" +
      "\001 \001(\0102\337\001\n\030PatientMonitoringService\022d\n\rGe" +
      "tVitalSigns\022\'.patientmonitoring.GetVital" +
      "SignsRequest\032(.patientmonitoring.GetVita" +
      "lSignsResponse\"\000\022]\n\rSetAlertValue\022\'.pati" +
      "entmonitoring.SetAlertValueRequest\032!.pat" +
      "ientmonitoring.Acknowledgment\"\000B&\n\023ds.zh" +
      "uldyz.service1B\rService1ProtoP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_patientmonitoring_GetVitalSignsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_patientmonitoring_GetVitalSignsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientmonitoring_GetVitalSignsRequest_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_patientmonitoring_GetVitalSignsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_patientmonitoring_GetVitalSignsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientmonitoring_GetVitalSignsResponse_descriptor,
        new java.lang.String[] { "BloodPressure", "Temperature", });
    internal_static_patientmonitoring_SetAlertValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_patientmonitoring_SetAlertValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientmonitoring_SetAlertValueRequest_descriptor,
        new java.lang.String[] { "PatientId", "BloodPressureValue", "TemperatureValue", });
    internal_static_patientmonitoring_Acknowledgment_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_patientmonitoring_Acknowledgment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_patientmonitoring_Acknowledgment_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
