// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service5.proto

package ds.zhuldyz.service5;

public final class Service5Proto {
  private Service5Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AppointmentRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:appointment.AppointmentRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string patient_id = 1;</code>
     */
    java.lang.String getPatientId();
    /**
     * <code>string patient_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getPatientIdBytes();

    /**
     * <code>string doctor_id = 2;</code>
     */
    java.lang.String getDoctorId();
    /**
     * <code>string doctor_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getDoctorIdBytes();

    /**
     * <code>string appointment_date = 3;</code>
     */
    java.lang.String getAppointmentDate();
    /**
     * <code>string appointment_date = 3;</code>
     */
    com.google.protobuf.ByteString
        getAppointmentDateBytes();
  }
  /**
   * Protobuf type {@code appointment.AppointmentRequest}
   */
  public  static final class AppointmentRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:appointment.AppointmentRequest)
      AppointmentRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppointmentRequest.newBuilder() to construct.
    private AppointmentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppointmentRequest() {
      patientId_ = "";
      doctorId_ = "";
      appointmentDate_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppointmentRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              patientId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              doctorId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              appointmentDate_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.zhuldyz.service5.Service5Proto.internal_static_appointment_AppointmentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.zhuldyz.service5.Service5Proto.internal_static_appointment_AppointmentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.zhuldyz.service5.Service5Proto.AppointmentRequest.class, ds.zhuldyz.service5.Service5Proto.AppointmentRequest.Builder.class);
    }

    public static final int PATIENT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object patientId_;
    /**
     * <code>string patient_id = 1;</code>
     */
    public java.lang.String getPatientId() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientId_ = s;
        return s;
      }
    }
    /**
     * <code>string patient_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPatientIdBytes() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCTOR_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object doctorId_;
    /**
     * <code>string doctor_id = 2;</code>
     */
    public java.lang.String getDoctorId() {
      java.lang.Object ref = doctorId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        doctorId_ = s;
        return s;
      }
    }
    /**
     * <code>string doctor_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDoctorIdBytes() {
      java.lang.Object ref = doctorId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        doctorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPOINTMENT_DATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object appointmentDate_;
    /**
     * <code>string appointment_date = 3;</code>
     */
    public java.lang.String getAppointmentDate() {
      java.lang.Object ref = appointmentDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appointmentDate_ = s;
        return s;
      }
    }
    /**
     * <code>string appointment_date = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAppointmentDateBytes() {
      java.lang.Object ref = appointmentDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appointmentDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPatientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, patientId_);
      }
      if (!getDoctorIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, doctorId_);
      }
      if (!getAppointmentDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, appointmentDate_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPatientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, patientId_);
      }
      if (!getDoctorIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, doctorId_);
      }
      if (!getAppointmentDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, appointmentDate_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.zhuldyz.service5.Service5Proto.AppointmentRequest)) {
        return super.equals(obj);
      }
      ds.zhuldyz.service5.Service5Proto.AppointmentRequest other = (ds.zhuldyz.service5.Service5Proto.AppointmentRequest) obj;

      boolean result = true;
      result = result && getPatientId()
          .equals(other.getPatientId());
      result = result && getDoctorId()
          .equals(other.getDoctorId());
      result = result && getAppointmentDate()
          .equals(other.getAppointmentDate());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPatientId().hashCode();
      hash = (37 * hash) + DOCTOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDoctorId().hashCode();
      hash = (37 * hash) + APPOINTMENT_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getAppointmentDate().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.zhuldyz.service5.Service5Proto.AppointmentRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code appointment.AppointmentRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:appointment.AppointmentRequest)
        ds.zhuldyz.service5.Service5Proto.AppointmentRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.zhuldyz.service5.Service5Proto.internal_static_appointment_AppointmentRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.zhuldyz.service5.Service5Proto.internal_static_appointment_AppointmentRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.zhuldyz.service5.Service5Proto.AppointmentRequest.class, ds.zhuldyz.service5.Service5Proto.AppointmentRequest.Builder.class);
      }

      // Construct using ds.zhuldyz.service5.Service5Proto.AppointmentRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        patientId_ = "";

        doctorId_ = "";

        appointmentDate_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.zhuldyz.service5.Service5Proto.internal_static_appointment_AppointmentRequest_descriptor;
      }

      @java.lang.Override
      public ds.zhuldyz.service5.Service5Proto.AppointmentRequest getDefaultInstanceForType() {
        return ds.zhuldyz.service5.Service5Proto.AppointmentRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ds.zhuldyz.service5.Service5Proto.AppointmentRequest build() {
        ds.zhuldyz.service5.Service5Proto.AppointmentRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.zhuldyz.service5.Service5Proto.AppointmentRequest buildPartial() {
        ds.zhuldyz.service5.Service5Proto.AppointmentRequest result = new ds.zhuldyz.service5.Service5Proto.AppointmentRequest(this);
        result.patientId_ = patientId_;
        result.doctorId_ = doctorId_;
        result.appointmentDate_ = appointmentDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.zhuldyz.service5.Service5Proto.AppointmentRequest) {
          return mergeFrom((ds.zhuldyz.service5.Service5Proto.AppointmentRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.zhuldyz.service5.Service5Proto.AppointmentRequest other) {
        if (other == ds.zhuldyz.service5.Service5Proto.AppointmentRequest.getDefaultInstance()) return this;
        if (!other.getPatientId().isEmpty()) {
          patientId_ = other.patientId_;
          onChanged();
        }
        if (!other.getDoctorId().isEmpty()) {
          doctorId_ = other.doctorId_;
          onChanged();
        }
        if (!other.getAppointmentDate().isEmpty()) {
          appointmentDate_ = other.appointmentDate_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.zhuldyz.service5.Service5Proto.AppointmentRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.zhuldyz.service5.Service5Proto.AppointmentRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object patientId_ = "";
      /**
       * <code>string patient_id = 1;</code>
       */
      public java.lang.String getPatientId() {
        java.lang.Object ref = patientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          patientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPatientIdBytes() {
        java.lang.Object ref = patientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder setPatientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        patientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder clearPatientId() {
        
        patientId_ = getDefaultInstance().getPatientId();
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder setPatientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        patientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object doctorId_ = "";
      /**
       * <code>string doctor_id = 2;</code>
       */
      public java.lang.String getDoctorId() {
        java.lang.Object ref = doctorId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          doctorId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string doctor_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDoctorIdBytes() {
        java.lang.Object ref = doctorId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          doctorId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string doctor_id = 2;</code>
       */
      public Builder setDoctorId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        doctorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string doctor_id = 2;</code>
       */
      public Builder clearDoctorId() {
        
        doctorId_ = getDefaultInstance().getDoctorId();
        onChanged();
        return this;
      }
      /**
       * <code>string doctor_id = 2;</code>
       */
      public Builder setDoctorIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        doctorId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appointmentDate_ = "";
      /**
       * <code>string appointment_date = 3;</code>
       */
      public java.lang.String getAppointmentDate() {
        java.lang.Object ref = appointmentDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appointmentDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appointment_date = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAppointmentDateBytes() {
        java.lang.Object ref = appointmentDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appointmentDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appointment_date = 3;</code>
       */
      public Builder setAppointmentDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appointmentDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appointment_date = 3;</code>
       */
      public Builder clearAppointmentDate() {
        
        appointmentDate_ = getDefaultInstance().getAppointmentDate();
        onChanged();
        return this;
      }
      /**
       * <code>string appointment_date = 3;</code>
       */
      public Builder setAppointmentDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appointmentDate_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:appointment.AppointmentRequest)
    }

    // @@protoc_insertion_point(class_scope:appointment.AppointmentRequest)
    private static final ds.zhuldyz.service5.Service5Proto.AppointmentRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.zhuldyz.service5.Service5Proto.AppointmentRequest();
    }

    public static ds.zhuldyz.service5.Service5Proto.AppointmentRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppointmentRequest>
        PARSER = new com.google.protobuf.AbstractParser<AppointmentRequest>() {
      @java.lang.Override
      public AppointmentRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppointmentRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppointmentRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppointmentRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.zhuldyz.service5.Service5Proto.AppointmentRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppointmentResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:appointment.AppointmentResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string appointment_id = 1;</code>
     */
    java.lang.String getAppointmentId();
    /**
     * <code>string appointment_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppointmentIdBytes();
  }
  /**
   * Protobuf type {@code appointment.AppointmentResponse}
   */
  public  static final class AppointmentResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:appointment.AppointmentResponse)
      AppointmentResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppointmentResponse.newBuilder() to construct.
    private AppointmentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppointmentResponse() {
      appointmentId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppointmentResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              appointmentId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.zhuldyz.service5.Service5Proto.internal_static_appointment_AppointmentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.zhuldyz.service5.Service5Proto.internal_static_appointment_AppointmentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.zhuldyz.service5.Service5Proto.AppointmentResponse.class, ds.zhuldyz.service5.Service5Proto.AppointmentResponse.Builder.class);
    }

    public static final int APPOINTMENT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object appointmentId_;
    /**
     * <code>string appointment_id = 1;</code>
     */
    public java.lang.String getAppointmentId() {
      java.lang.Object ref = appointmentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appointmentId_ = s;
        return s;
      }
    }
    /**
     * <code>string appointment_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppointmentIdBytes() {
      java.lang.Object ref = appointmentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appointmentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppointmentIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, appointmentId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppointmentIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, appointmentId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.zhuldyz.service5.Service5Proto.AppointmentResponse)) {
        return super.equals(obj);
      }
      ds.zhuldyz.service5.Service5Proto.AppointmentResponse other = (ds.zhuldyz.service5.Service5Proto.AppointmentResponse) obj;

      boolean result = true;
      result = result && getAppointmentId()
          .equals(other.getAppointmentId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPOINTMENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAppointmentId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.zhuldyz.service5.Service5Proto.AppointmentResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code appointment.AppointmentResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:appointment.AppointmentResponse)
        ds.zhuldyz.service5.Service5Proto.AppointmentResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.zhuldyz.service5.Service5Proto.internal_static_appointment_AppointmentResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.zhuldyz.service5.Service5Proto.internal_static_appointment_AppointmentResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.zhuldyz.service5.Service5Proto.AppointmentResponse.class, ds.zhuldyz.service5.Service5Proto.AppointmentResponse.Builder.class);
      }

      // Construct using ds.zhuldyz.service5.Service5Proto.AppointmentResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        appointmentId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.zhuldyz.service5.Service5Proto.internal_static_appointment_AppointmentResponse_descriptor;
      }

      @java.lang.Override
      public ds.zhuldyz.service5.Service5Proto.AppointmentResponse getDefaultInstanceForType() {
        return ds.zhuldyz.service5.Service5Proto.AppointmentResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ds.zhuldyz.service5.Service5Proto.AppointmentResponse build() {
        ds.zhuldyz.service5.Service5Proto.AppointmentResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.zhuldyz.service5.Service5Proto.AppointmentResponse buildPartial() {
        ds.zhuldyz.service5.Service5Proto.AppointmentResponse result = new ds.zhuldyz.service5.Service5Proto.AppointmentResponse(this);
        result.appointmentId_ = appointmentId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.zhuldyz.service5.Service5Proto.AppointmentResponse) {
          return mergeFrom((ds.zhuldyz.service5.Service5Proto.AppointmentResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.zhuldyz.service5.Service5Proto.AppointmentResponse other) {
        if (other == ds.zhuldyz.service5.Service5Proto.AppointmentResponse.getDefaultInstance()) return this;
        if (!other.getAppointmentId().isEmpty()) {
          appointmentId_ = other.appointmentId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.zhuldyz.service5.Service5Proto.AppointmentResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.zhuldyz.service5.Service5Proto.AppointmentResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object appointmentId_ = "";
      /**
       * <code>string appointment_id = 1;</code>
       */
      public java.lang.String getAppointmentId() {
        java.lang.Object ref = appointmentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appointmentId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appointment_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppointmentIdBytes() {
        java.lang.Object ref = appointmentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appointmentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appointment_id = 1;</code>
       */
      public Builder setAppointmentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appointmentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appointment_id = 1;</code>
       */
      public Builder clearAppointmentId() {
        
        appointmentId_ = getDefaultInstance().getAppointmentId();
        onChanged();
        return this;
      }
      /**
       * <code>string appointment_id = 1;</code>
       */
      public Builder setAppointmentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appointmentId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:appointment.AppointmentResponse)
    }

    // @@protoc_insertion_point(class_scope:appointment.AppointmentResponse)
    private static final ds.zhuldyz.service5.Service5Proto.AppointmentResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.zhuldyz.service5.Service5Proto.AppointmentResponse();
    }

    public static ds.zhuldyz.service5.Service5Proto.AppointmentResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppointmentResponse>
        PARSER = new com.google.protobuf.AbstractParser<AppointmentResponse>() {
      @java.lang.Override
      public AppointmentResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppointmentResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppointmentResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppointmentResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.zhuldyz.service5.Service5Proto.AppointmentResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service5.proto\022\013appointment\"U\n\022Appoint" +
      "mentRequest\022\022\n\npatient_id\030\001 \001(\t\022\021\n\tdocto" +
      "r_id\030\002 \001(\t\022\030\n\020appointment_date\030\003 \001(\t\"-\n\023" +
      "AppointmentResponse\022\026\n\016appointment_id\030\001 " +
      "\001(\t2l\n\022AppointmentService\022V\n\017BookAppoint" +
      "ment\022\037.appointment.AppointmentRequest\032 ." +
      "appointment.AppointmentResponse\"\000B&\n\023ds." +
      "zhuldyz.service5B\rService5ProtoP\000b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_appointment_AppointmentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_appointment_AppointmentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentRequest_descriptor,
        new java.lang.String[] { "PatientId", "DoctorId", "AppointmentDate", });
    internal_static_appointment_AppointmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_appointment_AppointmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentResponse_descriptor,
        new java.lang.String[] { "AppointmentId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
