// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service4.proto

package ds.zhuldyz.service4;

public final class Service4Proto {
  private Service4Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreatePrescriptionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:prescription.CreatePrescriptionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string patient_id = 1;</code>
     */
    java.lang.String getPatientId();
    /**
     * <code>string patient_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getPatientIdBytes();

    /**
     * <code>string doctor_id = 2;</code>
     */
    java.lang.String getDoctorId();
    /**
     * <code>string doctor_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getDoctorIdBytes();
  }
  /**
   * Protobuf type {@code prescription.CreatePrescriptionRequest}
   */
  public  static final class CreatePrescriptionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:prescription.CreatePrescriptionRequest)
      CreatePrescriptionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreatePrescriptionRequest.newBuilder() to construct.
    private CreatePrescriptionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreatePrescriptionRequest() {
      patientId_ = "";
      doctorId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreatePrescriptionRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              patientId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              doctorId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.zhuldyz.service4.Service4Proto.internal_static_prescription_CreatePrescriptionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.zhuldyz.service4.Service4Proto.internal_static_prescription_CreatePrescriptionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest.class, ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest.Builder.class);
    }

    public static final int PATIENT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object patientId_;
    /**
     * <code>string patient_id = 1;</code>
     */
    public java.lang.String getPatientId() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientId_ = s;
        return s;
      }
    }
    /**
     * <code>string patient_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPatientIdBytes() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOCTOR_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object doctorId_;
    /**
     * <code>string doctor_id = 2;</code>
     */
    public java.lang.String getDoctorId() {
      java.lang.Object ref = doctorId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        doctorId_ = s;
        return s;
      }
    }
    /**
     * <code>string doctor_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDoctorIdBytes() {
      java.lang.Object ref = doctorId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        doctorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPatientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, patientId_);
      }
      if (!getDoctorIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, doctorId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPatientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, patientId_);
      }
      if (!getDoctorIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, doctorId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest)) {
        return super.equals(obj);
      }
      ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest other = (ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest) obj;

      boolean result = true;
      result = result && getPatientId()
          .equals(other.getPatientId());
      result = result && getDoctorId()
          .equals(other.getDoctorId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPatientId().hashCode();
      hash = (37 * hash) + DOCTOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDoctorId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code prescription.CreatePrescriptionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:prescription.CreatePrescriptionRequest)
        ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.zhuldyz.service4.Service4Proto.internal_static_prescription_CreatePrescriptionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.zhuldyz.service4.Service4Proto.internal_static_prescription_CreatePrescriptionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest.class, ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest.Builder.class);
      }

      // Construct using ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        patientId_ = "";

        doctorId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.zhuldyz.service4.Service4Proto.internal_static_prescription_CreatePrescriptionRequest_descriptor;
      }

      @java.lang.Override
      public ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest getDefaultInstanceForType() {
        return ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest build() {
        ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest buildPartial() {
        ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest result = new ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest(this);
        result.patientId_ = patientId_;
        result.doctorId_ = doctorId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest) {
          return mergeFrom((ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest other) {
        if (other == ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest.getDefaultInstance()) return this;
        if (!other.getPatientId().isEmpty()) {
          patientId_ = other.patientId_;
          onChanged();
        }
        if (!other.getDoctorId().isEmpty()) {
          doctorId_ = other.doctorId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object patientId_ = "";
      /**
       * <code>string patient_id = 1;</code>
       */
      public java.lang.String getPatientId() {
        java.lang.Object ref = patientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          patientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPatientIdBytes() {
        java.lang.Object ref = patientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder setPatientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        patientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder clearPatientId() {
        
        patientId_ = getDefaultInstance().getPatientId();
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 1;</code>
       */
      public Builder setPatientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        patientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object doctorId_ = "";
      /**
       * <code>string doctor_id = 2;</code>
       */
      public java.lang.String getDoctorId() {
        java.lang.Object ref = doctorId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          doctorId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string doctor_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDoctorIdBytes() {
        java.lang.Object ref = doctorId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          doctorId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string doctor_id = 2;</code>
       */
      public Builder setDoctorId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        doctorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string doctor_id = 2;</code>
       */
      public Builder clearDoctorId() {
        
        doctorId_ = getDefaultInstance().getDoctorId();
        onChanged();
        return this;
      }
      /**
       * <code>string doctor_id = 2;</code>
       */
      public Builder setDoctorIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        doctorId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:prescription.CreatePrescriptionRequest)
    }

    // @@protoc_insertion_point(class_scope:prescription.CreatePrescriptionRequest)
    private static final ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest();
    }

    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreatePrescriptionRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreatePrescriptionRequest>() {
      @java.lang.Override
      public CreatePrescriptionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreatePrescriptionRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreatePrescriptionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreatePrescriptionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.zhuldyz.service4.Service4Proto.CreatePrescriptionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreatePrescriptionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:prescription.CreatePrescriptionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string medicine_name = 1;</code>
     */
    java.lang.String getMedicineName();
    /**
     * <code>string medicine_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getMedicineNameBytes();

    /**
     * <code>string dose = 2;</code>
     */
    java.lang.String getDose();
    /**
     * <code>string dose = 2;</code>
     */
    com.google.protobuf.ByteString
        getDoseBytes();
  }
  /**
   * Protobuf type {@code prescription.CreatePrescriptionResponse}
   */
  public  static final class CreatePrescriptionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:prescription.CreatePrescriptionResponse)
      CreatePrescriptionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreatePrescriptionResponse.newBuilder() to construct.
    private CreatePrescriptionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreatePrescriptionResponse() {
      medicineName_ = "";
      dose_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreatePrescriptionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              medicineName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              dose_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.zhuldyz.service4.Service4Proto.internal_static_prescription_CreatePrescriptionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.zhuldyz.service4.Service4Proto.internal_static_prescription_CreatePrescriptionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse.class, ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse.Builder.class);
    }

    public static final int MEDICINE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object medicineName_;
    /**
     * <code>string medicine_name = 1;</code>
     */
    public java.lang.String getMedicineName() {
      java.lang.Object ref = medicineName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        medicineName_ = s;
        return s;
      }
    }
    /**
     * <code>string medicine_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMedicineNameBytes() {
      java.lang.Object ref = medicineName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        medicineName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOSE_FIELD_NUMBER = 2;
    private volatile java.lang.Object dose_;
    /**
     * <code>string dose = 2;</code>
     */
    public java.lang.String getDose() {
      java.lang.Object ref = dose_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dose_ = s;
        return s;
      }
    }
    /**
     * <code>string dose = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDoseBytes() {
      java.lang.Object ref = dose_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dose_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMedicineNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, medicineName_);
      }
      if (!getDoseBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dose_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMedicineNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, medicineName_);
      }
      if (!getDoseBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dose_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse)) {
        return super.equals(obj);
      }
      ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse other = (ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse) obj;

      boolean result = true;
      result = result && getMedicineName()
          .equals(other.getMedicineName());
      result = result && getDose()
          .equals(other.getDose());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MEDICINE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMedicineName().hashCode();
      hash = (37 * hash) + DOSE_FIELD_NUMBER;
      hash = (53 * hash) + getDose().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code prescription.CreatePrescriptionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:prescription.CreatePrescriptionResponse)
        ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.zhuldyz.service4.Service4Proto.internal_static_prescription_CreatePrescriptionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.zhuldyz.service4.Service4Proto.internal_static_prescription_CreatePrescriptionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse.class, ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse.Builder.class);
      }

      // Construct using ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        medicineName_ = "";

        dose_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.zhuldyz.service4.Service4Proto.internal_static_prescription_CreatePrescriptionResponse_descriptor;
      }

      @java.lang.Override
      public ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse getDefaultInstanceForType() {
        return ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse build() {
        ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse buildPartial() {
        ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse result = new ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse(this);
        result.medicineName_ = medicineName_;
        result.dose_ = dose_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse) {
          return mergeFrom((ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse other) {
        if (other == ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse.getDefaultInstance()) return this;
        if (!other.getMedicineName().isEmpty()) {
          medicineName_ = other.medicineName_;
          onChanged();
        }
        if (!other.getDose().isEmpty()) {
          dose_ = other.dose_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object medicineName_ = "";
      /**
       * <code>string medicine_name = 1;</code>
       */
      public java.lang.String getMedicineName() {
        java.lang.Object ref = medicineName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          medicineName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string medicine_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMedicineNameBytes() {
        java.lang.Object ref = medicineName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          medicineName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string medicine_name = 1;</code>
       */
      public Builder setMedicineName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        medicineName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string medicine_name = 1;</code>
       */
      public Builder clearMedicineName() {
        
        medicineName_ = getDefaultInstance().getMedicineName();
        onChanged();
        return this;
      }
      /**
       * <code>string medicine_name = 1;</code>
       */
      public Builder setMedicineNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        medicineName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dose_ = "";
      /**
       * <code>string dose = 2;</code>
       */
      public java.lang.String getDose() {
        java.lang.Object ref = dose_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dose_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dose = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDoseBytes() {
        java.lang.Object ref = dose_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dose_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dose = 2;</code>
       */
      public Builder setDose(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dose_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dose = 2;</code>
       */
      public Builder clearDose() {
        
        dose_ = getDefaultInstance().getDose();
        onChanged();
        return this;
      }
      /**
       * <code>string dose = 2;</code>
       */
      public Builder setDoseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dose_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:prescription.CreatePrescriptionResponse)
    }

    // @@protoc_insertion_point(class_scope:prescription.CreatePrescriptionResponse)
    private static final ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse();
    }

    public static ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreatePrescriptionResponse>
        PARSER = new com.google.protobuf.AbstractParser<CreatePrescriptionResponse>() {
      @java.lang.Override
      public CreatePrescriptionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreatePrescriptionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreatePrescriptionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreatePrescriptionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.zhuldyz.service4.Service4Proto.CreatePrescriptionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prescription_CreatePrescriptionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prescription_CreatePrescriptionRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_prescription_CreatePrescriptionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_prescription_CreatePrescriptionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service4.proto\022\014prescription\"B\n\031Create" +
      "PrescriptionRequest\022\022\n\npatient_id\030\001 \001(\t\022" +
      "\021\n\tdoctor_id\030\002 \001(\t\"A\n\032CreatePrescription" +
      "Response\022\025\n\rmedicine_name\030\001 \001(\t\022\014\n\004dose\030" +
      "\002 \001(\t2\212\001\n\035PrescriptionManagementService\022" +
      "i\n\022CreatePrescription\022\'.prescription.Cre" +
      "atePrescriptionRequest\032(.prescription.Cr" +
      "eatePrescriptionResponse\"\000B&\n\023ds.zhuldyz" +
      ".service4B\rService4ProtoP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_prescription_CreatePrescriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_prescription_CreatePrescriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prescription_CreatePrescriptionRequest_descriptor,
        new java.lang.String[] { "PatientId", "DoctorId", });
    internal_static_prescription_CreatePrescriptionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_prescription_CreatePrescriptionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_prescription_CreatePrescriptionResponse_descriptor,
        new java.lang.String[] { "MedicineName", "Dose", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
